# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lars',
            fields=[
                ('qual_aim', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('qual_aim_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_rpt', models.BooleanField(default=False)),
                ('course_caution', models.BooleanField(default=False)),
                ('course_complete', models.BooleanField(default=False)),
                ('course_code', models.CharField(blank=True, max_length=20)),
                ('course_code_old', models.CharField(blank=True, max_length=20)),
                ('course_name', models.CharField(help_text=b'Enter a name that makes sense', max_length=200)),
                ('course_delivery', models.CharField(choices=[(b'FT', b'Full Time'), (b'PTQ', b'Part Time Qualification'), (b'HE', b'Higher Education'), (b'L2L', b'Love2Learn'), (b'APP', b'Apprenticeship')], default=b'FT', max_length=100)),
                ('course_type', models.CharField(choices=[(b'M', b'Main Aim'), (b'N', b'Nested Qualification'), (b'C', b'Child Code'), (b'S', b'Standalone Course'), (b'F', b'Functional Skills'), (b'G', b'Group Code'), (b'R', b'Register Code')], default=b'M', max_length=100)),
                ('strand', models.CharField(choices=[(b'A2H', b'Access to HE'), (b'ACC', b'Accommodation'), (b'AHC', b'Animal Care'), (b'APP', b'Apprenticeships'), (b'ART', b'Arts'), (b'ASC', b'Ascentis'), (b'BEA', b'Beauty'), (b'BER', b'Business Employer Responsive'), (b'BLS', b'Building Services Engineering'), (b'BRI', b'Bricklaying'), (b'BUS', b'Business'), (b'CAD', b'Careers Advice & Guidance'), (b'CAR', b'Care'), (b'CON', b'Construction (Somer Valley)'), (b'CPT', b'Carpentry'), (b'CST', b'Construction  CIBE'), (b'CVC', b'Cardiff and Vale College'), (b'DEU', b'Distance Education'), (b'DLH', b'Distance Learning (Highways/ILM)'), (b'DNG', b'Design'), (b'DWA', b'Development Worker A'), (b'ELI', b'Electrical'), (b'ELS', b'English Language School (inc. ESOL)'), (b'ELY', b'Early Years'), (b'ENG', b'Engineering'), (b'EXM', b'Exam Resiit Fees'), (b'FDN', b'Foundation Learning'), (b'FIN', b'Finance'), (b'FLO', b'Floristry'), (b'GCS', b'GCSEs'), (b'HAB', b'Hair & Beauty'), (b'HAI', b'Hair'), (b'HOR', b'Horticulture'), (b'HOS', b'Hospitality'), (b'INT', b'Information Technology'), (b'LCV', b'Learning Curve'), (b'MED', b'Media'), (b'MFL', b'Modern Foreign Languages'), (b'MOT', b'Motor Vehicle'), (b'MRK', b'Marketing'), (b'MTD', b'Business Professional'), (b'MUS', b'Music'), (b'NCC', b'NCC Skills Ltd'), (b'NGT', b'N-Gaged Training'), (b'ODC', b'One Day Course'), (b'OTH', b'Other Miscellaneous Codes'), (b'PAD', b'Painting & Decorating'), (b'PAR', b'Performing Arts'), (b'PBS', b'Public Services'), (b'PMB', b'Plumbing'), (b'PRE', b'Pre-16'), (b'PRM', b'Premier'), (b'REF', b'Refrigeration'), (b'SAA', b'Strand Area A'), (b'SAB', b'Strand Area B'), (b'SAC', b'Student Advice Centre'), (b'SFL', b'Skills for Life'), (b'SHC', b'Short Courses'), (b'SPO', b'Sport'), (b'STO', b'Stonemasonry'), (b'T2G', b'Train to Gain'), (b'TAS', b'Teaching Assistants'), (b'TNT', b'Travel & Tourism'), (b'TRP', b'Traineeship'), (b'TTR', b'Teacher Training'), (b'UFU', b'Units for the Unemployed'), (b'UOB', b'UoB International Foundation Year'), (b'UOL', b'UoL BSC Business'), (b'VAP', b'Vocational Access Programme'), (b'VET', b'Veterinary Nursing'), (b'XLR', b'Pre-16')], default=b'A2H', max_length=100)),
                ('department', models.CharField(choices=[(b'DACL', b'Dept of Adult and Community Learning'), (b'DCAE', b'Dept of Creative Arts and Enterprise'), (b'DEAM', b'Dept of English & Maths'), (b'DECC', b'Dept of Technology'), (b'DFDN', b'Dept of Foundation Learning'), (b'DHBS', b'Dept of Hospitality, Hair, Beauty and Spa Industries'), (b'DINT', b'Dept for International Studies'), (b'DLBS', b'Dept of Land Based Studies'), (b'DSLC', b'Dept of Sport, Leisure & Care'), (b'DSTB', b'Dept of Services to Business & Work Based Learning'), (b'DXDY', b'Dept of Specialist Delivery'), (b'MISC', b'Miscellaneous Codes & Fees (Agresso)')], default=b'DACL', max_length=100)),
                ('location', models.CharField(choices=[(b'CC', b'Bath - City Centre Campus'), (b'SV', b'Radstock - Somer Valley Campus'), (b'XX', b'Cross-College'), (b'EE', b'External / Employer')], default=b'CC', max_length=100)),
                ('qual_aim', models.CharField(max_length=10, null=True)),
                ('fee_comments', models.CharField(max_length=250)),
                ('day', models.CharField(max_length=100)),
                ('study_year', models.IntegerField(help_text=b"For courses with a duration of one year or less, this will always be '1'")),
                ('study_year_duration', models.IntegerField(help_text=b'How many years will this course take overall?')),
                ('parent_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.Offering')),
                ('qual_aim_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.Lars')),
            ],
        ),
    ]
