# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldOffering',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(blank=True, max_length=20)),
                ('course_name', models.CharField(help_text='Enter a name that makes sense', max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='lars',
            options={'verbose_name_plural': 'LARS Entries'},
        ),
        migrations.AddField(
            model_name='offering',
            name='exam_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offering',
            name='exam_fee_old',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offering',
            name='fcr_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offering',
            name='fcr_fee_old',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offering',
            name='glh',
            field=models.IntegerField(default=0, help_text='Total guided learning hours, including teaching and tutorials; does NOT include employability'),
        ),
        migrations.AddField(
            model_name='offering',
            name='materials_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offering',
            name='materials_fee_old',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offering',
            name='max_students',
            field=models.IntegerField(default=0, help_text='Maximum number of students that can be taught - total, not per group'),
        ),
        migrations.AddField(
            model_name='offering',
            name='min_students',
            field=models.IntegerField(default=0, help_text='Minimum number of students required for course to run / be financially viable'),
        ),
        migrations.AddField(
            model_name='offering',
            name='mkt_add_costs',
            field=models.TextField(default='', help_text='Are there any additional costs?'),
        ),
        migrations.AddField(
            model_name='offering',
            name='mkt_assess',
            field=models.TextField(default='', help_text='How will students be assessed?'),
        ),
        migrations.AddField(
            model_name='offering',
            name='mkt_bring',
            field=models.TextField(default='', help_text='What do students need to bring?'),
        ),
        migrations.AddField(
            model_name='offering',
            name='mkt_career',
            field=models.TextField(default='', help_text='Where might this course lead? What are the opportunities for progression both within the college and beyond?'),
        ),
        migrations.AddField(
            model_name='offering',
            name='mkt_course_name',
            field=models.CharField(default='', help_text='A shorter, easily understood title suitable for print and web, avoid technical language and abbreviations', max_length=250),
        ),
        migrations.AddField(
            model_name='offering',
            name='mkt_course_overview',
            field=models.TextField(default='', help_text='A general overview of the qualification or course'),
        ),
        migrations.AddField(
            model_name='offering',
            name='mkt_entry_req',
            field=models.TextField(default='', help_text='What are the entry requirements?'),
        ),
        migrations.AddField(
            model_name='offering',
            name='mkt_funding',
            field=models.TextField(default='', help_text='What funding options are available?'),
        ),
        migrations.AddField(
            model_name='offering',
            name='mkt_learning',
            field=models.TextField(default='', help_text='What are the learning / delivery methods? How will students learn?'),
        ),
        migrations.AddField(
            model_name='offering',
            name='mkt_other',
            field=models.TextField(default='', help_text='What else do students need to know?'),
        ),
        migrations.AddField(
            model_name='offering',
            name='mkt_prospectus',
            field=models.CharField(choices=[('NONE', 'None (do not advertise)'), ('FT', 'Full Time Prospectus'), ('PT', 'Part Time / Love2Learn Prospectus'), ('AP', 'Apprenticeship Prospectus'), ('FTAP', 'Full Time and Apprenticeship'), ('PTAP', 'Part Time and Apprenticeship'), ('FTPT', 'Full Time and Part Time'), ('ALL', 'All Prospectuses')], default='NONE', help_text='Which prospectuses (if any) would you like this course to appear in?', max_length=100),
        ),
        migrations.AddField(
            model_name='offering',
            name='mkt_target',
            field=models.TextField(default='', help_text='Who is the course aimed at?'),
        ),
        migrations.AddField(
            model_name='offering',
            name='mkt_topics',
            field=models.TextField(default='', help_text='What topics are covered?'),
        ),
        migrations.AddField(
            model_name='offering',
            name='mkt_tutor',
            field=models.TextField(default='', help_text='Who will teach the course? What are their credentials?'),
        ),
        migrations.AddField(
            model_name='offering',
            name='mkt_where',
            field=models.TextField(default='', help_text='Where will students need to go on their first day?'),
        ),
        migrations.AddField(
            model_name='offering',
            name='number_grps',
            field=models.IntegerField(default=0, help_text='How many groups will the course need?'),
        ),
        migrations.AddField(
            model_name='offering',
            name='number_wks',
            field=models.IntegerField(default=0, help_text='How many weeks will this course run for?'),
        ),
        migrations.AddField(
            model_name='offering',
            name='other_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offering',
            name='other_fee_old',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offering',
            name='tuition_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offering',
            name='tuition_fee_old',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offering',
            name='weighted_matrix',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offering',
            name='wk_hrs',
            field=models.IntegerField(default=0, help_text='How many hours of study per week?'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='course_delivery',
            field=models.CharField(choices=[('FT', 'Full Time'), ('PTQ', 'Part Time Qualification'), ('HE', 'Higher Education'), ('L2L', 'Love2Learn'), ('APP', 'Apprenticeship')], default='FT', max_length=100),
        ),
        migrations.AlterField(
            model_name='offering',
            name='course_name',
            field=models.CharField(help_text='Enter a name that makes sense', max_length=200),
        ),
        migrations.AlterField(
            model_name='offering',
            name='course_type',
            field=models.CharField(choices=[('M', 'Main Aim'), ('N', 'Nested Qualification'), ('C', 'Child Code'), ('S', 'Standalone Course'), ('F', 'Functional Skills'), ('G', 'Group Code'), ('R', 'Register Code')], default='M', max_length=100),
        ),
        migrations.AlterField(
            model_name='offering',
            name='department',
            field=models.CharField(choices=[('DACL', 'Dept of Adult and Community Learning'), ('DCAE', 'Dept of Creative Arts and Enterprise'), ('DEAM', 'Dept of English & Maths'), ('DECC', 'Dept of Technology'), ('DFDN', 'Dept of Foundation Learning'), ('DHBS', 'Dept of Hospitality, Hair, Beauty and Spa Industries'), ('DINT', 'Dept for International Studies'), ('DLBS', 'Dept of Land Based Studies'), ('DSLC', 'Dept of Sport, Leisure & Care'), ('DSTB', 'Dept of Services to Business & Work Based Learning'), ('DXDY', 'Dept of Specialist Delivery'), ('MISC', 'Miscellaneous Codes & Fees (Agresso)')], default='DACL', max_length=100),
        ),
        migrations.AlterField(
            model_name='offering',
            name='location',
            field=models.CharField(choices=[('CC', 'Bath - City Centre Campus'), ('SV', 'Radstock - Somer Valley Campus'), ('XX', 'Cross-College'), ('EE', 'External / Employer')], default='CC', max_length=100),
        ),
        migrations.AlterField(
            model_name='offering',
            name='strand',
            field=models.CharField(choices=[('A2H', 'Access to HE'), ('ACC', 'Accommodation'), ('AHC', 'Animal Care'), ('APP', 'Apprenticeships'), ('ART', 'Arts'), ('ASC', 'Ascentis'), ('BEA', 'Beauty'), ('BER', 'Business Employer Responsive'), ('BLS', 'Building Services Engineering'), ('BRI', 'Bricklaying'), ('BUS', 'Business'), ('CAD', 'Careers Advice & Guidance'), ('CAR', 'Care'), ('CON', 'Construction (Somer Valley)'), ('CPT', 'Carpentry'), ('CST', 'Construction  CIBE'), ('CVC', 'Cardiff and Vale College'), ('DEU', 'Distance Education'), ('DLH', 'Distance Learning (Highways/ILM)'), ('DNG', 'Design'), ('DWA', 'Development Worker A'), ('ELI', 'Electrical'), ('ELS', 'English Language School (inc. ESOL)'), ('ELY', 'Early Years'), ('ENG', 'Engineering'), ('EXM', 'Exam Resiit Fees'), ('FDN', 'Foundation Learning'), ('FIN', 'Finance'), ('FLO', 'Floristry'), ('GCS', 'GCSEs'), ('HAB', 'Hair & Beauty'), ('HAI', 'Hair'), ('HOR', 'Horticulture'), ('HOS', 'Hospitality'), ('INT', 'Information Technology'), ('LCV', 'Learning Curve'), ('MED', 'Media'), ('MFL', 'Modern Foreign Languages'), ('MOT', 'Motor Vehicle'), ('MRK', 'Marketing'), ('MTD', 'Business Professional'), ('MUS', 'Music'), ('NCC', 'NCC Skills Ltd'), ('NGT', 'N-Gaged Training'), ('ODC', 'One Day Course'), ('OTH', 'Other Miscellaneous Codes'), ('PAD', 'Painting & Decorating'), ('PAR', 'Performing Arts'), ('PBS', 'Public Services'), ('PMB', 'Plumbing'), ('PRE', 'Pre-16'), ('PRM', 'Premier'), ('REF', 'Refrigeration'), ('SAA', 'Strand Area A'), ('SAB', 'Strand Area B'), ('SAC', 'Student Advice Centre'), ('SFL', 'Skills for Life'), ('SHC', 'Short Courses'), ('SPO', 'Sport'), ('STO', 'Stonemasonry'), ('T2G', 'Train to Gain'), ('TAS', 'Teaching Assistants'), ('TNT', 'Travel & Tourism'), ('TRP', 'Traineeship'), ('TTR', 'Teacher Training'), ('UFU', 'Units for the Unemployed'), ('UOB', 'UoB International Foundation Year'), ('UOL', 'UoL BSC Business'), ('VAP', 'Vocational Access Programme'), ('VET', 'Veterinary Nursing'), ('XLR', 'Pre-16')], default='A2H', max_length=100),
        ),
        migrations.AlterField(
            model_name='offering',
            name='study_year',
            field=models.IntegerField(default=0, help_text="For courses with a duration of one year or less, this will always be '1'"),
        ),
        migrations.AlterField(
            model_name='offering',
            name='study_year_duration',
            field=models.IntegerField(default=0, help_text='How many years will this course take overall?'),
        ),
    ]
