# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_auto_20170426_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='course_name',
            field=models.CharField(help_text='Please follow syntax: [Subject][Qualification][Level][(Extra Information)]. E.g. Plumbing Diploma L3 (Day Release)', max_length=200),
        ),
        migrations.AlterField(
            model_name='offering',
            name='day',
            field=models.CharField(choices=[('Various', 'FT - Multiple Days'), ('Weds/Thurs/Fri', 'Weds/Thurs/Fri'), ('Weds/Fri', 'Weds/Fri'), ('Wednesday', 'Wednesday'), ('Wed/Thurs', 'Wed/Thurs'), ('Tuesday', 'Tuesday'), ('Tues/Wed/Thurs/Fri', 'Tues/Wed/Thurs/Fri'), ('Tues/Wed/Thurs', 'Tues/Wed/Thurs'), ('Tues/Wed', 'Tues/Wed'), ('Tues/Thurs', 'Tues/Thurs'), ('Tues/Fri', 'Tues/Fri'), ('Thursday', 'Thursday'), ('Thurs/Sat', 'Thurs/Sat'), ('Thurs/Fri', 'Thurs/Fri'), ('Sunday', 'Sunday'), ('Saturday', 'Saturday'), ('Mon-Fri', 'Mon-Fri'), ('Monday', 'Monday'), ('Mon/Wed', 'Mon/Wed'), ('Mon/Tues/Wed/Thurs', 'Mon/Tues/Wed/Thurs'), ('Mon/Tues/Fri', 'Mon/Tues/Fri'), ('Mon/Tues', 'Mon/Tues'), ('Mon/Thurs', 'Mon/Thurs'), ('Mon/Fri', 'Mon/Fri'), ('Friday', 'Friday')], default='Various', help_text="Only required for part time courses, if full time, leave set to 'FT - Multiple Days'", max_length=100),
        ),
        migrations.AlterField(
            model_name='offering',
            name='exam_fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offering',
            name='exam_fee_old',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offering',
            name='fcr_fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offering',
            name='fcr_fee_old',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offering',
            name='fee_comments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='offering',
            name='materials_fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offering',
            name='materials_fee_old',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offering',
            name='min_students',
            field=models.IntegerField(default=5, help_text='Minimum number of students required for course to run / be financially viable'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='number_grps',
            field=models.IntegerField(default=1, help_text='How many groups will the course need?'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='other_fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offering',
            name='other_fee_old',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offering',
            name='qual_aim_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.Lars'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='study_year',
            field=models.IntegerField(default=1, help_text="For courses with a duration of one year or less, this will always be '1'"),
        ),
        migrations.AlterField(
            model_name='offering',
            name='study_year_duration',
            field=models.IntegerField(default=1, help_text='How many years will this course take overall?'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='tuition_fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offering',
            name='tuition_fee_old',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offering',
            name='weighted_matrix',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
