# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_auto_20170426_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='end_date',
            field=models.DateField(default='2019-06-30'),
        ),
        migrations.AddField(
            model_name='offering',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='offering',
            name='start_date',
            field=models.DateField(default='2018-08-01'),
        ),
        migrations.AddField(
            model_name='offering',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
